# Generated by Django 5.1.7 on 2025-05-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0002_products_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveBigIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.products_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.reg_tbl')),
            ],
        ),
    ]
